### PR TITLE
Fix active rooms end time display

### PR DESCRIPTION
**Pull request by nanaya**
Turns out end time is nullable.

### CODE REVIEW

**Review by notbakaneko — CHANGES_REQUESTED** [review]
Actually, what's the display ordering supposed to be if the room doesn't end? 🤔

**Comment by nanaya** [comment]
There's a default `id` tie breaker.

**Comment by notbakaneko** [comment]
`order by ends_at desc` puts null at the bottom, is this what we want, though? 👀

**Comment by nanaya** [comment]
That can be fixed/discussed separately I think

**Comment by nanaya** [comment]
oh cool mysql doesn't even have `nulls [first | last]` operator 😐

**Pull request merged**
