### PR TITLE
Made the italian translation

### PR DESCRIPTION
**Pull request by marcostudios**
Sorry for making you worry ppy and everyone on discord 😅 

It's not 100% perfect because some words or phrases doesn't have a direct translation but at least the bigger part is done 👍 

Well..anybody that can speak/write in Italian are welcome to help with this

### CODE REVIEW

**Comment by nanaya** [comment]
- [newlines](https://en.wikipedia.org/wiki/Newline) need to be changed to unix.
- add locale definition to `config/app.php` and `app/Libraries/LocaleMeta.php`.

(if not sure about the second one, just fix the newlines for now. Merging in the styleci suggestion should be enough)

**Comment by marcostudios** [comment]
hey @nanaya how can i change the newline to unix? do  i need to use a unix/linux distro or what?

**Comment by nanaya** [comment]
if you're using vs code, it's the `files.eol` option (unix is `\n`).  Other editors should have similar setting as well.

**Comment by marcostudios** [comment]
Done

**Comment by leonekmi** [comment]
You must apply the StyleCI .diff file if you want to be merged.

**Comment by aerouk** [comment]
Won't pass StyleCI if you have a trailing comma in the array.

line 91: `'it',` should be `'it'`

**Comment by cl8n** [comment]
I believe the error comes from the missing comma after `'pt-br'` on line 90. StyleCI references line 91 because it's mistakenly looking for the end of the array there.

**Comment by leonekmi** [comment]
Hey @marcostudios, i created a PR in your fork to fix your problem, just merge if you want.

**Comment by marcostudios** [comment]
Thanks but it still fails on travis

**Comment by RedNesto** [comment]
You must remove the comma following the last member of the list.

**Comment by leonekmi** [comment]
.PHP Fatal error:  Cannot declare class App\Libraries\LocaleMeta, because the name is already in use in /home/travis/build/ppy/osu-web/config/LocaleMeta.php on line 22

You have placed LocaleMeta.php in config/ folder. Delete it

**Comment by marcostudios** [comment]
Thank you 👍

**Pull request merged**
