### PR TITLE
Update all files to use PSR-2

### PR DESCRIPTION
**Pull request by ameliaikeda**
Also I changed my name in the composer file. This is a pretty huge update; merge conflicts on existing PRs ahoy.

### CODE REVIEW

**Comment by nanaya** [comment]
it doesn't fix blade templates, does it? :(

**Comment by ameliaikeda** [comment]
It should avoid them, because tabs vs spaces in those files can cause visual changes (like replacing tab sequences with `&nbsp;`)

**Comment by nanaya** [comment]
tabs to spaces is okay, I think. Not sure how it can go from tabs to html entity though.

**Comment by ameliaikeda** [comment]
Tabs don't appear as a space in a browser, while a space does (I meant to say *similar to `&nbsp;`*). It's a small edge-case, but it's probably why the styleci guys chose not to run on those files.

**Comment by nanaya** [comment]
pretty sure spaces and tabs are squashed (`    ` behaves the same as ` `) in html.

**Comment by nanaya** [comment]
I'm not sure about `align_double_arrow` fixer. It looks nice but adding key longer than existing keys means realigning entire thing.

**Comment by nanaya** [comment]
enable `unalign_double_arrow` as well, I guess.

**Comment by ameliaikeda** [comment]
Will do~

**Comment by nanaya** [comment]
and then squash them all \o/

**Comment by peppy** [comment]
\o:

**Pull request merged**
