### PR TITLE
Align join date to top on forum posts

### PR DESCRIPTION
**Pull request by Carlos-T**
Fixes [#435](https://github.com/ppy/osu-web/issues/435)
So no space between flag and join date.
image

### CODE REVIEW

**Comment by cl8n** [comment]
pretty sure it's intended to be bottom-anchored

**Comment by Carlos-T** [comment]
What's the issue point then? a max-height? :) a common behaviour should be defined, no matter how long is the post.

**Comment by peppy** [comment]
@arflyte

**Comment by arflyte** [comment]
Updating the poster detail area design

**Pull request merged**
