### PR TITLE
Swedish Language Support

### PR DESCRIPTION
**Pull request by Padnezz**
For now, ability to select Swedish on the site is added
Contents from assets/lang/en has been copied to assets/lang/sv

Not done yet, but I'll update this PR as files are translated and when I'm done

### CODE REVIEW

**Comment by Padnezz** [comment]
About 25% done

**Comment by Padnezz** [comment]
About 60% done

**Comment by Padnezz** [comment]
100% done according to my text editor, will do a final test locally before removing "WIP" from the title

**Comment by Padnezz** [comment]
All is done!

**Comment by kj415j45** [comment]
:tada: you'd better ask some Swedish to review your translations. however, if no one reviewed, your pr can be merged in some days ¯\_(ツ)_/¯

**Comment by Padnezz** [comment]
I have some people who can check it out (no GitHub accounts though)

**Comment by Padnezz** [comment]
Two of my friends have reviewed the translation and no errors were found.

**Comment by peppy** [comment]
Thank you for your hard work on this! 🥇

**Pull request merged**
