### PR TITLE
Add country flag tooltips in wiki

### LINKED ISSUE #10661: Country flags in osu! wiki don't have tooltips
They used to have tooltips before the custom syntax. Maybe also link them to the country rankings to be consistent with all the other flags on the site.

Note that lazer already has tooltips but not the linking.

### PR DESCRIPTION
**Pull request by Swekka**
Closes #10661

### CODE REVIEW

**Comment by Swekka** [comment]
The tests aren't working as I'd expect, if you look at the [first test failure](https://github.com/ppy/osu-web/actions/runs/6603821744/job/17937338932#step:11:141) it says:

`1) Tests\Libraries\Markdown\ProcessorTest::testHtml with data set #1 ('attribute_flag', '/home/runner/work/osu-web/osu...amples')
ErrorException: Attempt to read property "acronym" on null`

Meaning `Country::find("AU")` was somehow `null`

**Review by notbakaneko — CHANGES_REQUESTED** [review]
I'm pretty sure we don't want to be doing a db query for every single flag

**Comment by Swekka** [comment]
Makes sense, what would be the best way to do this without a db query?

**Comment by Swekka** [comment]
I just realized that if `AU` happens to be in the test db the test will always fail, but I have no idea what to do about that since the countries in the test db are always random

**Comment by notbakaneko** [comment]
I don't think we want to make a network request to redis for every flag either; use a local cache like https://github.com/ppy/osu-web/blob/3b91b06/app/Libraries/Groups.php or https://github.com/ppy/osu-web/blob/3b91b06/app/Libraries/Medals.php does it.

**Comment by notbakaneko** [comment]
I mean making a service object to cache the country names like `Groups` does and adding it to `AppServiceProvider` https://github.com/ppy/osu-web/blob/master/app/Providers/AppServiceProvider.php#L39-L43

**Review by notbakaneko — CHANGES_REQUESTED** [review]
Fetch the countries (preferably just the name and country code) once, store it in an a `Map` or keyed array and do the lookup against the `Map/array` as needed.

**Review by notbakaneko — CHANGES_REQUESTED** [review]
```php
    private function allByCode(): Collection
    {
        return $this->memoize(__FUNCTION__, fn () => Country::get(['acronym', 'name'])->keyBy('acronym'));
    }

    public function byCode(string $code): ?Country
    {
        return $this->allByCode()->get($code);
    }
```

**Review by notbakaneko — APPROVED** [review]

**Pull request merged**
