### PR TITLE
Include score in osu_scores_high index

### PR DESCRIPTION
**Pull request by notbakaneko**
so the index covers the query in https://github.com/ppy/osu-web/issues/1873#issue-278523250

Adds a new index and drops the old one.
Creating the index will take a while 🔥

### CODE REVIEW

**Comment by peppy** [comment]
What is the score being used for in this query?

**Comment by notbakaneko** [comment]
some calculation thing

**Comment by peppy** [comment]
Need more specific details. This is not an arbitrary index change, and will take 3-4 days to update and increase the overall database size by a non-trivial amount.

**Comment by notbakaneko** [comment]
closing in favour of storing the missing counts

**Pull request closed without merging**
