### PR TITLE
Update wiki.php

### PR DESCRIPTION
**Pull request by pimpG**
small translation

### CODE REVIEW

**Comment by TPGPL** [comment]
Thanks for your contribution, although all web translation changes are made through [Crowdin](https://crowdin.com/project/osu-web). so you should make changes there instead

**Comment by pimpG** [comment]
this is not available to translate there it seems?
it shows pt-br translation is 100%

**Comment by TPGPL** [comment]
it's because Crowdin hasn't been updated with the newest page changes (e.g. wiki main page) so there are no strings for that yet; you should wait till it gets updated and then suggest translations

**Comment by peppy** [comment]
crowdin translations are updated on a weekly basis. if it's not available please wait until the next update.

**Pull request closed without merging**
