### PR TITLE
Improve wiki search

### PR DESCRIPTION
**Pull request by nanaya**
- title field has highest priority
- (cleaned up) path field has higher priority (requires reindexing)
- limit search in current locale

Incoming complains from people using other locales can't search english wiki pages.

### CODE REVIEW

**Comment by peppy** [comment]
Hmm, may be a good idea to always search english as well (just give it lower priority maybe)

**Comment by nanaya** [comment]
I looked at it but it's beyond me at the moment. Need to read more.

**Comment by peppy** [comment]
💯

**Comment by peppy** [comment]
well, :99: (let's fix the english fallback at some point)

**Comment by notbakaneko** [comment]
I'd consider having a separate fields for each locale instead a `locale` field, then we can do a multi_match on the locale's field and english

**Pull request merged**
