### PR TITLE
Add tooltip for registered players count

### LINKED ISSUE #3461: Add tooltip to "players" icon on tournament
Kinda self explained, since the icon is bit ambiguous (can be translated as number of players who plays or number of players who registered on tournament)
screenshot

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/60532035-add-tooltip-to-players-icon-on-tournament?utm_campaign=plugin&utm_content=tracker%2F21853994&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F21853994&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by nanaya**
Fixes #3461, not sure about the wordings.

---

### CODE REVIEW

**Comment by notbakaneko** [comment]
`:count players registered` maybe?

**Comment by nanaya** [comment]
The number would be rather redundant? Also other icon description tooltips in user page and beatmapset page don't seem have it either.

**Comment by notbakaneko** [comment]
It's not a call to action nor does clicking on the icon do or show anything specific to the tooltip's description, so, it should really include the number imo; otherwise, the tooltip should be limited specifically to the icon portion only.

**Comment by nanaya** [comment]
So this should be changed to only appear on the icon as well, I guess?

**Comment by notbakaneko** [comment]
yes, it should

**Pull request merged**
