### PR TITLE
grammar/typo fixes

### PR DESCRIPTION
**Pull request by Remyria**
grammar/typo fixes

### CODE REVIEW

**Comment by kj415j45** [comment]
you can put them( #1036 #1037 #1038 #1039  ) in 1 PR,rather than 4(or more)

**Comment by Remyria** [comment]
I don't know how ^^"

**Comment by Remyria** [comment]
I don't have permissions to merge

**Comment by kj415j45** [comment]
of course you can't merge,

> Only those with write access to this repository can merge pull requests.

peppy,nanaya(maybe) have write access,you can just PR then update it then wait for merged

**Pull request closed without merging**
