### PR TITLE
Ability to remove userpages

### PR DESCRIPTION
**Pull request by cl8n**
... by soft-deleting the post and breaking the relationship to it

this way, users can actually get rid of the "me!" tab instead of just reducing it to a tiny bar

### CODE REVIEW

**Comment by cl8n** [comment]
there's a small issue with styling where the icons won't stay visible when hovering over the right half of their box. I'm not sure how to fix ;_;

**Comment by nanaya** [comment]
Looks like this will prevent people with previous supporter tag (but not anymore) from creating user page after deleting it.

**Comment by nanaya** [comment]
There's already code to hide the userpage when it's empty but it needs updating.

**Comment by cl8n** [comment]
added in #1777

**Pull request closed without merging**
