### PR TITLE
Fix 24h osu!catch scores from lazer missing count50 values

### PR DESCRIPTION
**Pull request by smoogipoo**
Found this as I'm reading through the new infrastructure planning.

### CODE REVIEW

**Comment by nanaya** [comment]
I think it was skipped because it's not shown anywhere on web (and doesn't exist in old score?).

**Comment by smoogipoo** [comment]
Oh, hang on. This goes the other way around and I derped hard.

Right, I see. So this is basically only relevant for the 24h rolling scores, if I'm understanding the code correctly? I suppose it's fine to lose data here because these aren't stored forever there's no display?

**Comment by smoogipoo** [comment]
> and doesn't exist in old score?

As for this, I believe that scores from stable do populate count50 for osu!catch in this table.

**Comment by nanaya** [comment]
Hm yeah so it's not currently shown anywhere for other reason then...?

**Comment by smoogipoo** [comment]
Today I learnt :smile: Fine to close this if you think it's okay as is.

**Comment by peppy** [comment]
I think there's no harm in fixing this as long as the mapping is correct?

**Review by nanaya — APPROVED** [review]

**Comment by nanaya** [comment]
I assume it means the same thing in stable...

**Comment by smoogipoo** [comment]
I've double confirmed that it does.

**Comment by nanaya** [comment]
Should we show it in score table on web? 🤔

**Comment by smoogipoo** [comment]
For highscores (which this doesn't apply to, so it's a separate issue altogether), lazer shows the leaderboard in the form `hit/total`:
image
(Ignore the lack of spacing on the columns)

Neither lazer nor osu-web display scores in the `osu-scores` 24hr rolling table anywhere other than as a detail-less panel on the user page:
image

That being said, I believe there are third party website addons that show each judgement specifically (and I suppose they could be queried via the API).

**Pull request merged**
