### PR TITLE
Allow overriding default font

### LINKED ISSUE #3169: Broken texts in Vietnamese localisation
Yes because Exo 2 doesn't support Vietnamese.

I was told to find a new one to use for the Vietnamese localisation but not sure how to choose so I'll leave that for the designer 😛 

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/58227872-broken-texts-in-vietnamese-localisation?utm_campaign=plugin&utm_content=tracker%2F21853994&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F21853994&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by nanaya**
With the magic of CSS variable. Doesn't work in IE.

The whole site looks kind of weird though...

Fixes #3169.

### CODE REVIEW

**Comment by nekodex** [comment]
Not sure this is the correct approach? This won't fix Vietnamese text being broken for anyone not using the Vietnamese locale... e.g. on the beatmap pages, etc?

**Comment by nanaya** [comment]
The alternative is finding Vietnamese version of exo 2 because it shares alphabet with Latin.

**Comment by shortthu** [comment]
Can't find any Vietnamese version of Exo 2 with Google (using Vietnamese keywords) so there is no hope finding it unless someone do it.
Only Exo 1 have a Vietnamese version though.

**Comment by shortthu** [comment]
Well I think the fix is enough because not many people uses Vietnamese in the beatmap page or forum anyway.

**Comment by kj415j45** [comment]
It seems that this is a good solution for #2866 too. We'll try to find the best order and font for zh.

**Pull request merged**
