### PR TITLE
Move beatmap attributes to per-beatmap document

### PR DESCRIPTION
**Pull request by nanaya**
This will allow searching for beatmaps with specific combination of attributes.

For example, searching for beatmap with difficulty rating of 3 and drain rate of 8 using the old structure may return beatmapset which contain two different beatmaps, one with diff 3 (but maybe drain 7) and another one with drain 8 (but maybe diff 4).

This is required to match lazer behavior for advanced query search.

Removed the old attributes except playmodes because it's the field still in use by legacy web although I think it could be easily updated to use the nested one?

### CODE REVIEW

**Comment by peppy** [comment]
I'm willing to update the legacy code to work with the new location. Or you can, I think you have access.

**Comment by nanaya** [comment]
Apparently nested document can't be easily searched using query string syntax which legacy web uses.

**Comment by peppy** [comment]
okay let's not.

**Review by notbakaneko — APPROVED** [review]

**Review by notbakaneko — COMMENTED** [review]
reindex not necessary until #7300

**Review by notbakaneko — APPROVED** [review]

**Pull request merged**
