### PR TITLE
Improve user search ordering

### PR DESCRIPTION
**Pull request by nanaya**
Add tie-breaker based on last visit so online users (who are not invisible) are more visible when using prefix search.

Maybe? 🤔 

Related: #8360

### CODE REVIEW

**Review by notbakaneko — CHANGES_REQUESTED** [review]
shouldn't it always be `('user_lastvisit', 'desc')`? it seems weird to prioritize by online and then flip it when the ordering changes 🤔

**Comment by nanaya** [comment]
the idea is when you sort it by the other way the order should come up in the other way and not "the other way except when tie breaking then it'll always be the same order"

**Comment by notbakaneko** [comment]
using `username.raw` as the tiebreaker for prefix search makes more sense, imo.

**Comment by notbakaneko** [comment]
prefix search with username sort will return something like 
```
abc prefix
prefixa abc
prefixb abc
prefixz abc
zzz prefix
```

while `_score, username.raw` should return something more like
```
prefixa abc
prefixb abc
prefixz abc
abc prefix
zzz prefix
```

and with just `_score` it's free-for-all order 🤔

**Comment by nanaya** [comment]
There seems to be some weirder cases like with three words name etc but it's already pretty weird anyway so ┐( ﾟ ヮﾟ)┌

**Comment by nanaya** [comment]
...this `username.raw` sort is case sensitive isn't it

**Review by notbakaneko — APPROVED** [review]

**Pull request merged**
