### PR TITLE
Fix cover-editor being below page-extra-tabs

### PR DESCRIPTION
**Pull request by RockRoller01**
#7909 increased the z-index to prevent beatmap-card borders to be above the extra tabs, however this lead to the cover selector being below them now.

image

Increased the editors index and left a note that it must be at least 1 higher than extra-tabs

### CODE REVIEW

**Comment by nanaya** [comment]
It's actually kinda expected as the floating bar at the bottom is considered the same as menu bar at the top

I have no problem either way but if we're going with this, at least the line should be moved according to the actual value which should've been obvious if you look at the whole section.

**Comment by RockRoller01** [comment]
ah I didn't see that these are listed in increasing order. Will change in a bit. imo this must be changed as the tabs otherwise cover up the information on the cover, leaving people clueless as to size and supporter requirement

**Comment by nanaya** [comment]
You can scroll the page down to see it...

**Comment by RockRoller01** [comment]
> You can scroll the page down to see it...

no you actually can not, the cover uploader is stuck in position

**Comment by nanaya** [comment]
> no you actually can not, the cover uploader is stuck in position

:thinking:

**Comment by RockRoller01** [comment]
ah i see why you dont see the issue. Apparently a very specific setup is needed:

- ranking folded in
- 1 row of badges
- 
image

**Review by nanaya — APPROVED** [review]

**Pull request merged**
