### PR TITLE
Show favourite beatmaps on user profile in reverse favourited order

### PR DESCRIPTION
**Pull request by notbakaneko**
sort of related to #1944

tried adding an index to `dateadded` for sorting but mysql didn't seem to want to use it

### CODE REVIEW

**Comment by peppy** [comment]
What's the reason for dropping back to raw sql?

**Comment by notbakaneko** [comment]
`hasManyThrough` doesn't work on composite keys and the ordering needs to be done on the intermediary table; we can't just select ids and select `Beatmapset` since that won't return the correct order.

**Comment by peppy** [comment]
lame

**Comment by notbakaneko** [comment]
apparently this is breaking search :|

**Pull request merged**
