### PR TITLE
Fix an error in README.md

### PR DESCRIPTION
**Pull request by kj415j45**
`php -s [files]` means 

> Output HTML syntax highlighted source.

but `php -S <addr>:<port>` 

> Run with built-in web server.

### CODE REVIEW

**Comment by ZLima12** [comment]
`-s` is an entirely different parameter, and caused some confusion when I was first trying it out. +1

**Comment by nanaya** [comment]
(it's probably better to just `php artisan serve` though)

**Comment by kj415j45** [comment]
So Can I add it into README?@nanaya

**Comment by nanaya** [comment]
┐(ﾟ ヮﾟ)┌

**Comment by kj415j45** [comment]
I try to test it
But after I use `sudo ./build.sh`
and `php artisan serve`

It crash with

> 192.168.253.1:52878 [500]: / - Uncaught InvalidArgumentException: File css/app.css not defined in asset manifest. in /home/kj415j45/osu-web/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:411
> Stack trace:
> #0 /home/kj415j45/osu-web/storage/framework/views/0fbc08e37449c05cf15132c3e42c372bf51ae060.php(21): elixir('css/app.css')
> #1 /home/kj415j45/osu-web/bootstrap/cache/compiled.php(15631): include('/home/kj415j45/...')
> #2 /home/kj415j45/osu-web/bootstrap/cache/compiled.php(15668): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/kj415j45/...', Array)
> #3 /home/kj415j45/osu-web/bootstrap/cache/compiled.php(15500): Illuminate\View\Engines\CompilerEngine->get('/home/kj415j45/...', Array)
> #4 /home/kj415j45/osu-web/bootstrap/cache/compiled.php(15488): Illuminate\View\View->getContents()
> #5 /home/kj415j45/osu-web/bootstrap/cache/compiled.php(15472): Illuminate\View\View->renderContents()
> #6 /home/kj415j45/osu-web/storage/framework/views/4a57ac7efa9fac1444319613a0b025600abc41f4.php(5): Illuminate\View\View->render()
> #7 /home/kj41 in /home/kj415j45/osu-web/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 411
> 

What should I do?

**Comment by kj415j45** [comment]
It seems that I lost a CSS called app.css

**Comment by kj415j45** [comment]
maybe it's 

> https://github.com/laravel/laravel/tree/master/public/css/app.css

but why add it into composer

I don't know how to edit composer file,so could you add it? @nanaya

**Comment by nanaya** [comment]
generate the assets.

**Comment by kj415j45** [comment]
What do you mean???

**Comment by nanaya** [comment]
read the readme

**Pull request merged**
