### PR TITLE
Account for retina size team flag

### PR DESCRIPTION
**Pull request by nanaya**
Either this or just make it a quarter of its current size on team page instead (display size of 128x64). Especially considering they're pretty tiny everywhere else.

### CODE REVIEW

**Comment by notbakaneko** [comment]
I think it can just use retina size everywhere, the downscaling quality isn't going to make much difference on non-retina displays imo. The file size for larger pngs is more of an issue if they're being used everywhere for the small flags, etc...

**Comment by nanaya** [comment]
using 512x256 image for 40x20 display just sounds silly...

**Comment by notbakaneko** [comment]
That's what I said in a different way

**Comment by nanaya** [comment]
Apparently we're going with this for now so we have the highest possible images and can add smaller version later (either an additional file column or resizing service through nginx or whatever)

**Comment by peppy** [comment]
To give a bit more context, I think uploading and storing the larger 256x512 is best for now specifically to match the height of avatars and to give the most flexibility to team creators and to future usages of the graphics, ie. news posts or tournament overlays.

**Review by peppy — APPROVED** [review]
i think

**Review by notbakaneko — APPROVED** [review]

**Pull request merged**
