### PR TITLE
Add option to automatically subscribe to topics when posting

### PR DESCRIPTION
**Pull request by cl8n**
possible solution for #4379

---

### CODE REVIEW

**Comment by peppy** [comment]
I still think that this should be forced for the help forum, on top of potentially having this option as well.

Also this thing used to exist with phpbb, and still exists in the database (so you don't need to add a new column) - check `user_notify` I believe.

**Comment by cl8n** [comment]
since the problem seems to be that newer users won't follow up on their threads, I think this option could be set true for everyone at first? or is that too forceful idk

will add the help forum thing if not that instead^

**Comment by peppy** [comment]
The help forum one should bypass the setting 100%. The actual user setting was switched to "off" by default because of email spam, but once we have the ability to discern emails from notificaitons we'll probably set it to "on" for notifications "off" for email by default.

**Comment by cl8n** [comment]
I can't reproduce the error here D:

**Pull request merged**
