### PR TITLE
Ignore broken beatmap archive for cover regeneration

### PR DESCRIPTION
**Pull request by nanaya**
For some reason there are beatmaps with invalid zip file ಠ_ಠ

### CODE REVIEW

**Review by notbakaneko — CHANGES_REQUESTED** [review]
I think there should be a change to the metrics being recorded in `RegenerateBeatmapsetCover` if it fails on invalid zip? 🤔

**Comment by nanaya** [comment]
I think it's the same as any other ignored cases unless we want to track them all which then would be a different pr.

**Comment by notbakaneko** [comment]
What's the reason does this get recorded as `ok` instead of `error`?

**Comment by nanaya** [comment]
Because it'll be fixed once the file is fixed. The same as missing file and invalid format.

**Review by notbakaneko — APPROVED** [review]

**Pull request merged**
