### PR TITLE
add traditional chinese localisation support

### LINKED ISSUE #2071: LocaleMeta updates: Chinese (Simplified/Traditional/Cantonese)
According to @osu-translate-zh 's recent discussion, LocaleMeta will be updated in zh-patch-10.
根据 @osu-translate-zh 近期的讨论结果，我们将在10号补丁中更新 LocaleMeta 。

Here's the planing: (ISO 639-1 Variants)
下面是更新计划：（ISO 639-1 变体）

~~zh: 中文(CN)~~ //Remove because no second selector menu for dialect 由于不为方言提供二级选择菜单而移除
zh-cn: 简体中文(CN)
zh-tw: 繁体中文(TW)
zh-hk: 粤语(HK)

Then we will rename zh -> zh-cn, both on wiki and web.
同时我们重命名现有全部 zh 为 zh-cn ，本操作会涉及 wiki
 和 web 。

This issue is for public discussion before patch being applied.
本 issue 将在补丁应用之前用于公开讨论。

This issue is also reference with #2070 ，about dialect.
本 issue 同时与 #2070 相关，关于方言。

### PR DESCRIPTION
**Pull request by Deardrops**
The meaning of chinese `locale` will be changed as follow:

| Locale | Description                              | 中文     |
|:-------|:-----------------------------------------|:---------|
| zh     | Simple Chinese                           | 简体中文 |
| zh-tw  | Traditional Chinese (Taiwan Standard)    | 臺灣正體 |
| zh-hk  | Traditional Chinese (Hong Kong Standard) | 香港繁體 |

This Pr is aim to add `zh-tw` localisation support in `osu-web`.

convent simple chinese to traditional chinese by [OpenCC](https://github.com/BYVoid/OpenCC)
reviewed by @edisonlee55 

see also:
osu-translate-zh/osu-web#7

close #2071 

All work finished.

### CODE REVIEW

**Comment by Deardrops** [comment]
To avoid rename all `zh.md` file to `zh-hans.md` in osu-wiki,
maybe we could use the origial `locale`，but change the meaning of them

| Locale | Description                              | 中文     |
|:-------|:-----------------------------------------|:---------|
| zh     | Simple Chinese                           | 简体中文 |
| zh-tw  | Traditional Chinese (Taiwan Standard)    | 臺灣正體 |
| zh-hk  | Traditional Chinese (Hong Kong Standard) | 香港繁體 |

**Comment by notbakaneko** [comment]
is this related to #2071?

**Comment by edisonlee55** [comment]
Yes, we are now also renaming Chinese LocaleMeta to `zh`/`zh-tw`/`zh-hk`.

**Comment by kj415j45** [comment]
Approved. 
Suggest squash since we finally decide to continue use zh, zh-tw and zh-hk. @Deardrops , plz edit PR description.

Besides, if squash, plz add these to squash commit description to avoid missing author
```
Co-authored-by: edisonlee55 <edisonlee@edisonlee55.com>
Co-authored-by: Deardrops <lness@qq.com>
```

**Pull request merged**
