### PR TITLE
Added OpenSearch support

### PR DESCRIPTION
**Pull request by YellowberryHN**
I saw that https://github.com/ppy/osu-web/issues/4728 has been open since 2019, and I figured I could do it, since it's a rather small thing that could be potentially helpful to many people.

I have only one concern, the OpenSearch spec says the `opensearch.xml` should be served with the Content-Type of `application/opensearchdescription+xml`, however in my testing it worked fine. It may be a problem for other browsers, so it's something to consider for later, but I personally have no idea how to do that.

### CODE REVIEW

**Comment by alchzh** [comment]
I wonder if there should be a separate search spec for just beatmap search.

**Comment by nanaya** [comment]
The problem with doing it this way is it hardcodes to `osu.ppy.sh` for all instances. This may get confusing for people testing on other places.

**Comment by YellowberryHN** [comment]
> The problem with doing it this way is it hardcodes to `osu.ppy.sh` for all instances. This may get confusing for people testing on other places.

I had this concern as well, if you have a suggestion on how that could be solved, I'd love to hear it.

**Comment by cl8n** [comment]
you'll need to serve it from application to do that, so make a route and blade template. see `testflight` route for a similar basic example. the `ext_view` function that sends blade view can also set content-type

**Comment by nanaya** [comment]
Continued to #9916.

**Pull request closed without merging**
