### PR TITLE
Add perfect combo check for solo scores

### PR DESCRIPTION
**Pull request by nanaya**
`legacy_perfect` only exists on scores from `osu_scores{mode}_high`.

### CODE REVIEW

**Comment by nanaya** [comment]
yes, according to @smoogipoo . Although now I think about it I don't know if that also applies to lazer scores (or if it's decided at all)

**Comment by smoogipoo** [comment]
Mania in lazer doesn't have the same quirk as stable, so yes you can just ensure there's no `miss` or `large_tick_miss`.

Also I don't know how osu!web decides perfect for stable scores, because it doesn't seem to be just absence of misses but rather absence of anything < `hit_200`? Notice score #20 for example:
image

**Comment by nanaya** [comment]
Currently it's based on the `perfect` flag in the score itself.

**Comment by smoogipoo** [comment]
Jesus.
```csharp
if ((CurrentScore.CountMiss + CurrentScore.Count50 + CurrentScore.Count100) == 0 && ((float)CurrentScore.CountKatu / CurrentScore.TotalHits) < 0.1)
    CurrentScore.Perfect = true;
else
    CurrentScore.Perfect = false;
```
So no misses/50/100s and less than 10% 200s. Yeah just go via statistics for lazer :sweat_smile:

**Review by notbakaneko — APPROVED** [review]
ok then 👀

**Pull request merged**
