### PR TITLE
osu!wiki - inline <code/> style

### PR DESCRIPTION
**Pull request by kj415j45**
fix inline code issue #1104 

- Now \<code\/\> looks better

maybe need some color scheme suggestion.

### CODE REVIEW

**Comment by nekodex** [comment]
I've updated #1104 with the design from @arflyte

**Comment by kj415j45** [comment]
If nothing wrong,it should look like this. Please check it if its design is good @nekodex 
image

**Comment by nekodex** [comment]
Yeah, this doesn't look like the design flyte provided.

**Comment by kj415j45** [comment]
you mean  use   
  border-color: `#222222`
?

**Comment by kj415j45** [comment]
~~But I think current style is just ok~~

**Comment by arflyte** [comment]
Inline code design https://puu.sh/vZKMk/c44d97ed4a.png

**Comment by kj415j45** [comment]
how about <pre/>codeblock?

**Comment by nekodex** [comment]
The code blocks should look _exactly_ like the design flyte provided:


Also the inline style should be as @arflyte added above:

**Comment by kj415j45** [comment]
ok,will update it(~~go to school now~~)

**Comment by kj415j45** [comment]
Current style:
image

**Comment by arflyte** [comment]
it's there if the code block has a title.

**Comment by nekodex** [comment]
There's no rounded corners in the design, also the background colour is wrong?

**Comment by kj415j45** [comment]
I'm not sure about how to deal with code block with title :/

inline `<code/>` has rounded corners in design....

I use color picker in `Microsoft drawing` to pick up the color....

**Comment by TPGPL** [comment]
Inline has, but block hasnt

**Comment by nekodex** [comment]
As @TPGPL said, and the background colour should be `#222222`

**Comment by kj415j45** [comment]
I see, I mixed `border-radius` with `border`'s first args :p

**Comment by kj415j45** [comment]
image

**Comment by nekodex** [comment]
Oh btw you can use `#222` and `#111` as shorthand for `#222222` and `#111111`

**Pull request merged**
