### PR TITLE
Clearer score rank indicator

### PR DESCRIPTION
**Pull request by nanaya**
not achieved = <del>0.25</del> 0.1 opacity and grayscale
achieved rank = normal opacity
lower than achieved rank = <del>0.5</del> 0.4 opacity

<details>
<summary>before</summary>

</details>

<details>
<summary>after</summary>

</details>

### CODE REVIEW

**Comment by arflyte** [comment]
Make it to 0.1, normal, 0.3

**Comment by nanaya** [comment]
@arflyte this? The unachieved ones seem a bit invisible at 0.1?

**Comment by arflyte** [comment]
I think it's okay to make the unachieved almost invisible, like their hope and dreams. As for the lower ones, I think 0.4 would be better instead of 0.3, slightly more visible.

**Comment by nanaya** [comment]
@arflyte

**Comment by arflyte** [comment]
Yeah, looks good to me.

**Review by notbakaneko — APPROVED** [review]

**Pull request merged**
