### PR TITLE
Fix missing gap after comments on changelog page

### LINKED ISSUE #9593: Missing gap after comments section on changelog
Just a minor visual thing, but afaik there should be a gap after the comments container, however its quite clearly filled on changelog comments.

how it should be:
image

how it is on changelogs:
image

### PR DESCRIPTION
**Pull request by RockRoller01**
closes #9593 

tested for both mobile and desktop

### CODE REVIEW

**Review by notbakaneko — COMMENTED** [review]
https://github.com/ppy/osu-web/issues/9593#issuecomment-1559349453

**Comment by RockRoller01** [comment]
@notbakaneko addressed all the ones in the comment and found some others

**Review by notbakaneko — CHANGES_REQUESTED** [review]
After investigating the layout some more, I think it makes more sense to move the `margin-bottom` to the base `osu-page` itself and have a modifier with `margin-bottom: 0` to override as necessary - there's also a bunch of inner elements that have margin-bottom which aren'y necessary if it's on the container instead

**Comment by RockRoller01** [comment]
I thought the very same thing, but I am not quite sure which of the classes are for components and which for actual layouts, so I didn't go with that route, as I wouldn't know which pages to check

**Comment by notbakaneko** [comment]
I'll probably make the updates in a separate PR

**Comment by RockRoller01** [comment]
@notbakaneko so is there anything blocking this PR considering that you wanted to the other fix in a seperate PR?

**Comment by notbakaneko** [comment]
@RockRoller01 I mean I'm going to move the margin to the base style and remove them from the inner elements, instead

**Comment by notbakaneko** [comment]
#10435

**Pull request closed without merging**
