### PR TITLE
remove outdated info about kudosu stars

### PR DESCRIPTION
**Pull request by pavlukivan**
they were replaced with hypes, right? In that case available kudosu info is irrelevant nowadays.

### CODE REVIEW

**Comment by peppy** [comment]
If this is to be removed, the underlying translation keys should be to. Also please give a visual context of which part you're removing (screenshot or something similar).

**Comment by pavlukivan** [comment]
Before | after
image

**Comment by pavlukivan** [comment]
Alternatively, it can be replaced with something like "kudosu earned last month" which would be somewhat useful

**Comment by venix12** [comment]
well, wouldn't kudosu earned still make some sense? guess the intended direction is to ever make it useable?

**Comment by pavlukivan** [comment]
I meant "replace kudosu available with kudosu earned last month", not "replace kudosu earned with kudosu earned last month"

**Comment by venix12** [comment]
ah yes, kudosu available i mean, sorry

**Comment by pavlukivan** [comment]
well, that's not up to me to decide

**Comment by notbakaneko** [comment]
@peppy are we going to go ahead with removing this?

**Comment by peppy** [comment]
Hmm... I guess there's no harm in hiding it for the time being.

**Pull request merged**
