### PR TITLE
included more content and translation to forum.php

### PR DESCRIPTION
**Pull request by HWSKY**
this file was originally translated according to /lang/em/forum.php root file
all translations and dependencies are fully included in this file since the last change, commit: 15b9668

### CODE REVIEW

**Comment by HWSKY** [comment]
please review this commit, apparently styleci database is outdated, it does not recognize the last file of the file contents: new_reply; forums; pin; watch;
I catch all content from the last file included at lang/em/forum.php. But the styleci still signals the undefined terms cited are unknown.

**Comment by peppy** [comment]
The changes styleci wants are obvious?

**Comment by HWSKY** [comment]
I do not know if it's obvious or not, but what he's asking for is something that already exists in lang/en /forum.php root file.

**Comment by HWSKY** [comment]
Please, if possible , take a time and tell me why styleci check has failed. Solving this bug I will learn how to deal with future translations that have the same issue.

**Comment by peppy** [comment]
You do know if you login on styleci it will actually offer to fix the issues for you, right?

image

**Comment by HWSKY** [comment]
i'm so embarrassed, is really hard to note that exists one more space, this styleci is (a ridiculous perfectionist) amazing. Thanks for help PPY.

**Comment by peppy** [comment]
Can you squash all these changes to a single commit?

**Comment by HWSKY** [comment]
sry, but i don't know how to remove last commits from a pull request, should i delete this pull and send another?

**Pull request closed without merging**
