### PR TITLE
Change the capitalization of permalinks in comments

### PR DESCRIPTION
**Pull request by TPGPL**
Changed the capitalization of permalinks in comments as it isn't fully correct in every language to capitalize the first letter of *every* word.

---

### CODE REVIEW

**Comment by notbakaneko** [comment]
Can you provide examples of this?

**Comment by TPGPL** [comment]
@notbakaneko currently permalink is Polish is translated as "odnośnik bezpośredni" and with capitalize it becomes "Odnośnik Bezpośredni" which isnt fully correct because capitalizing first letter of every word doesnt make sense in this language

**Comment by nekodex** [comment]
I'm thinking that all the comment actions should probably just be lower-case instead. Not sure why they were title-cased at all in the first place?


(see comment 1 vs comment 2)

**Comment by TPGPL** [comment]
should be ready now

**Comment by nekodex** [comment]
The other items (reply, edit, etc) are currently capitalised in the translation files, so they'll need to be transformed to lowercase, see:

**Comment by qcl12345** [comment]
I think this also ended up affecting the reply username as well when it probably shouldn't have?

e.g. https://osu.ppy.sh/comments/868955 and https://osu.ppy.sh/comments/868968 
The usernames that these people are replying to both have capital letters in them so they probably shouldn't be changed.

**Comment by peppy** [comment]
Reported as #4565.

**Pull request merged**
