### PR TITLE
New multiplayer room type

### PR DESCRIPTION
**Pull request by nanaya**
Add parameter `category` of `realtime` (also for listing). `ends_at` parameter can be skipped.

And then I noticed there's no way to indicate number of people inside the room :thinking: 

Todo:
- [x] test

### CODE REVIEW

**Comment by smoogipoo** [comment]
I think realtime rooms should not be returned if `category` is not present. Since these are technically different systems (at least client side), "any" only applies to playlists:

```
Multiplayer categories:
- realtime

Playlists categories:
- any
- normal
- spotlight
```

**Comment by peppy** [comment]
we should probably just *require* a type to be specified, or make it part of the route?

**Comment by smoogipoo** [comment]
Seems like omitting the `category` parameter doesn't return any rooms. It should return rooms with `category = NULL | spotlight`. The client does not send `category` to retrieve normal rooms, but it can do so (becomes `NULL | normal | spotlight`).

**Comment by nanaya** [comment]
Do you have any active rooms...?

**Comment by smoogipoo** [comment]
Yeah I do:

image

After forcing 'normal' category in the DB:

image

**Comment by nanaya** [comment]
oh huh I messed up the enum defaults

**Comment by peppy** [comment]
@notbakaneko can you do a check over this? would like to get it live for further testing of the full (backend) deployment.

**Review by notbakaneko — CHANGES_REQUESTED** [review]

**Review by notbakaneko — APPROVED** [review]

**Comment by peppy** [comment]
Migrations are fine to run via deploy.

**Pull request merged**
