### PR TITLE
Fix BBCode parsing to insert '<p></p>' instead of '<br />'

### PR DESCRIPTION
**Pull request by kcaze**
Fix for ppy/osu-web#29.

### CODE REVIEW

**Comment by peppy** [comment]
Able to rebase this on the latest master to fix the CI build error?

**Comment by kcaze** [comment]
I think I am based on the latest master?

**Comment by nanaya** [comment]
create test case for what you're fixing and update the other test cases

**Comment by nanaya** [comment]
and seems like travis is ignoring the addons settings as well :( will look into it later

**Comment by kcaze** [comment]
Updated the BBCode test cases to reflect my changes. And yeah, the other pull requests are also having the same Travis build issues.

**Comment by nanaya** [comment]
Not sure having an empty `<p>` a good idea.

**Comment by nanaya** [comment]
also, where's the new test case for the problem being fixed?

**Comment by Tewki** [comment]
Just a question, why not use a real bbcode engine/library like well jBBCode instead of purifying?

Also kcaze, empty dom elements is not a good idea

**Comment by nanaya** [comment]
because phpbb transforms input bbcode into its custom format (suffixing tags with uid `[b]` is stored as `[b:$uid]`).

**Comment by Tewki** [comment]
Yea but that can be accounted for in jBBCode + other libraries.

**Comment by nanaya** [comment]
feel free to try. It will need to at least pass the test without modification at `.db.txt` files and few modifications to `.html`.

**Comment by Tewki** [comment]
I can do it in a few hours when I get back from work if no one else has, also later on wouldn't it be good to drop those uid suffixes since peppy is pretty much leaving phpbb fully.

**Comment by nanaya** [comment]
yeah, but unfortunately there are currently quite a lot of missing functionalities in new forum.

**Comment by kcaze** [comment]
Yeah, you're right that using `<p></p>` is probably not a good idea. Go ahead and try jBBCode since I'm going to go to sleep soon.

**Pull request closed without merging**
