### PR TITLE
Add seasons infrastructure and basic display

### PR DESCRIPTION
**Pull request by venix12**
(a big) part of https://github.com/ppy/osu-web/issues/8736 :sparkles:

image

### CODE REVIEW

**Comment by venix12** [comment]
am i doing something wrong or is lint just having a stroke 🤨

**Comment by notbakaneko** [comment]
It means the new code added more warnings; we set a max limit on warnings for existing code, new code should not be adding lint errors or new warnings.

If running `yarn lint` returns the same number of warnings, you may need to clear the lint cache.

**Comment by venix12** [comment]
Well, no matter what I tried, I got 158 on both this branch and master, tried clearing cache too. 🤷

**Comment by nanaya** [comment]
Is it intentional allowing room to be potentially part of multiple seasons?

Also conflicts.

**Comment by venix12** [comment]
> Is it intentional allowing a room to be potentially part of multiple seasons?

It is, see https://github.com/ppy/osu-web/issues/8736#issuecomment-1155514126.

**Comment by nanaya** [comment]
I don't think the comment has any conclusion on that, just wondering it could be a possibility

**Comment by nanaya** [comment]
that looks more like on which way to do one to many (as per the question), not whether it should be one or many to many

**Comment by venix12** [comment]
Right... guess we could go with one-to-many and extend to many-to-many if/when needed then?

**Comment by venix12** [comment]
remember to never use git rebase irresponsibly! 

replaced by #9725 as it's probably way easier than fixing this one =D

**Pull request closed without merging**
