### PR TITLE
Convert store columns to fixed precision

### PR DESCRIPTION
**Pull request by notbakaneko**

### CODE REVIEW

**Comment by nanaya** [comment]
And then it becomes string when accessed through laravel...

**Comment by notbakaneko** [comment]
so it does ಠ_ಠ

**Comment by nanaya** [comment]
bcmath time...? ಠ_ಠ

**Comment by peppy** [comment]
are we ok to merge this in its current state?

**Comment by notbakaneko** [comment]
should be safe ™️

**Pull request merged**
