### PR TITLE
Change floating navigation view

### PR DESCRIPTION
**Pull request by gagahpangeran**
Closed https://github.com/ppy/osu-web/issues/6018

Based on this design https://github.com/ppy/osu-web/issues/6018#issuecomment-637350615

**User page navigation**
Screenshot from 2020-07-08 12-30-02

**Beatmap discussion page navigation**
Currently I can't check it because I don't know how to create beatmap discussion page. Need help how to create it.

### CODE REVIEW

**Comment by TheWildTree** [comment]
This doesn't really resemble the linked design though?

**Comment by gagahpangeran** [comment]
> This doesn't really resemble the linked design though?

Currently I only change the box width from screen width to page width. The background and border color are based on page variable color, so it's different color in user page.

I'm not sure about change the border to top, because it becomes separator between page and navigation box when sticky on top.

**border bottom**
Screenshot from 2020-07-08 18-37-59
Screenshot from 2020-07-08 18-38-15

**border top**
Screenshot from 2020-07-08 18-39-05
Screenshot from 2020-07-08 18-39-20

Any suggestion?

**Comment by TheWildTree** [comment]
The design uses brighter background colour for that part, which I think was intended to make it stand out a bit without the bottom border. You should give that a try and see how it looks.

**Comment by gagahpangeran** [comment]
I change it.

Screenshot from 2020-07-08 19-18-12

Screenshot from 2020-07-08 19-18-22

**Comment by gagahpangeran** [comment]
> **Beatmap discussion page navigation**
> Currently I can't check it because I don't know how to create beatmap discussion page. Need help how to create it.

I still need help for this because the navigation in that page have same behavior.

**Comment by gagahpangeran** [comment]
I check the navigation box in beatmap discussion page and only change the width.
image

Should I change the border to top too?

**Comment by notbakaneko** [comment]
Please wait a moment while we confirm some details of the design

**Comment by gagahpangeran** [comment]
**user page navigation**
image

**beatmap discussion page navigation**
image

**Pull request merged**
