### PR TITLE
Wiki Page

### PR DESCRIPTION
**Pull request by MasterBugPatch**
This is the initial wiki page creation

### CODE REVIEW

**Comment by peppy** [comment]
Does it still display correctly for you? Seems like some upstream changes may have broken it slightly:

**Comment by MasterBugPatch** [comment]
It looks like everything works in your screenshot except for the header image I have in there, do you have the header image locally?

**Comment by peppy** [comment]
The page is no longer in the correct containers, and spews out to the sides. Here's a better shot:

**Comment by MasterBugPatch** [comment]
Okay, I'll make changes accustomed to it. Should I make the side navigation hidden on mobile or smaller screens?

**Comment by peppy** [comment]
Yeah, that's probably a good direction to go.

**Comment by MasterBugPatch** [comment]
Got it, thanks for the help :).

**Comment by TPGPL** [comment]
@peppy need any help with transporting articles to new.ppy.sh?

**Comment by flashwave** [comment]
@TPGPL pretty sure it's just going to use the mediawiki database, like how the forum uses the phpbb database

**Comment by nanaya** [comment]
Design and stuff have been changed and then implemented.

**Pull request closed without merging**
