### PR TITLE
Add users.read API scope

### LINKED ISSUE #4798: Add scope to users endpoints
Please add a scope to the `api/v2/users/{user}/` endpoints to make them accessible.

### PR DESCRIPTION
**Pull request by cl8n**
assuming these routes are ready to be made public

closes #4798

### CODE REVIEW

**Comment by notbakaneko** [comment]
If it's for public-only data, I'm not sure it should be going through the third-party authorization grant flow? (and the scope would probably be called `public` or something)

**Comment by Aergwyn** [comment]
If I had a bot that would use public endpoints would that just send client id and secret in the headers to associate the request? Completely skipping the authorization or how did you imagine it?

**Comment by notbakaneko** [comment]
Client ID and secret are used to get the oauth token; how that token is obtained and the permissions granted depend on whether it's a third-party client acting on behalf of a user or not.

**Comment by notbakaneko** [comment]
Closing this as this is not how we want the scopes and authorization to work; non-privileged public data should be using a public grant that doesn't allow the token to act as the use that authorized it.

**Comment by nekodex** [comment]
To elaborate on what notbakaneko said:

Currently there's privileged information being returned by the API (e.g. account moderation info/metadata inside `/users/xxx` responses for users within the moderation group/etc) that we don't want third-party clients to get by default when granting basic "user read" permissions.

So we're gonna move out all the privileged info into separate permission group(s) first before we open up endpoints that could expose that data (so that for example, moderators don't accidentally leak privileged info to third-parties without realising).

**Pull request closed without merging**
