### PR TITLE
Make french locale available and configured

### PR DESCRIPTION
**Pull request by leonekmi**
I just forget to make language avivable in pull #753 , my bad.

## _Changes :_
- config/app.php (Add fr to config for Laravel Translation service)
- app/Libraries/LocaleMeta.php (reordering and added French(Français) to the file)

### CODE REVIEW

**Comment by nanaya** [comment]
- wrong target branch; should be `master` instead of `release`.
- need to add language information to `app/Libraries/LocaleMeta.php`.

**Comment by leonekmi** [comment]
Oh, thanks for the precision, i don't know so much Laravel Framework,

and yes i have changed the target branch

**Comment by nanaya** [comment]
Language name should be in its native language (for example 日本語 for Japanese). I don't know about French but pretty sure it's not called "French" in French.

Also would be nice if it's located in the same order as in `app.php`.

**Comment by nanaya** [comment]
Also, what's "avivable"? It doesn't seem to be an English word. Looking for it in French doesn't seem to have relevant meaning either.

**Comment by leonekmi** [comment]
Oh, i want say **available**, sorry and yes i pushed the fixes

**Pull request merged**
