### PR TITLE
Fix maximum statistics attribute not being stored

### PR DESCRIPTION
**Pull request by nanaya**
Uh ( ﾟ ヮﾟ)

@peppy, if client has been sending it, it's never stored in the db.

### CODE REVIEW

**Comment by smoogipoo** [comment]
Does this also need to be added to the multiplayer controller?

**Review by smoogipoo — APPROVED** [review]

**Comment by peppy** [comment]
Not a huge deal, we can just re-run the migration script (was planning to anyway to make sure).

Regarding multiplayer scores, I believe the end goal is still to combine the multiplayer and solo scores tablet into one.

**Review by notbakaneko — APPROVED** [review]
Is this fine to merge now?

**Comment by smoogipoo** [comment]
It's fine by me.

**Pull request merged**
