### PR TITLE
Add name header to store listings

### PR DESCRIPTION
**Pull request by comentarinformal**

### CODE REVIEW

**Comment by peppy** [comment]
I have a feeling this was omitted on purpose in the design. @arflyte?

**Comment by peppy** [comment]
Can you provide a screenshot showing how this changes the page?

**Comment by peppy** [comment]
Talking through this with @arflyte and @nanaya, this is actually intended so we can display different text in these places.

**Comment by comentarinformal** [comment]
Hmh, alright then

**Pull request closed without merging**
