### PR TITLE
implemenTed supporter page design

### PR DESCRIPTION
**Pull request by UnnoTed**
https://github.com/ppy/osu-web/issues/343

supports localization
and easily extensible (supporter perks and support's blocks)
template kinda responsive

preview: https://i.imgur.com/MsIkF5r.png

### CODE REVIEW

**Comment by peppy** [comment]
On a quick pass-over, one thing to note is that help.support is actually a different page from this one. This would probably fit better as community.support.

**Comment by UnnoTed** [comment]
anything else so i can fix all at once?

**Comment by peppy** [comment]
I'll need to check it out and look over it. Will definitely do so today, just a bit later!

**Comment by peppy** [comment]
Here's some things I've noticed:

- Button cut off when window width is mobile-sized

- The logic behind the top header section is weird. Have a look how it's done on the forum and/or store and do it in a similar way. You don't need absolute positioning or custom z-index.
- We're moving away from bootstrap, so it'd be better if you use flexbox for the boxes on the page.

**Comment by Nicarim** [comment]
It doesn't use BEM, does it.

**Comment by UnnoTed** [comment]
updaTed

**Comment by peppy** [comment]
I'll bring up a few remaining issues which would be great if you can look into, but I'm also going to award the bounty to you in advance.

- The top image has the drop shadow included, where as it should actually be in the css style (already present on http://new.ppy.sh/store/product/1 for reference).
- Maximum height of header should be limited in pixels, as per the design. At the moment it gets way too tall.
- Images should have @2x versions.

**Comment by peppy** [comment]
Will need to make a few changes to the assets, but merging this for now!

**Pull request merged**
