### PR TITLE
Use country flags from twemoji project

### LINKED ISSUE #3760: Several flags have incorrect details
Migrated from ppy/osu-resources#43. Since April, a few of the issues have been fixed. Here are the important ones which remain:

* Cambodia (`KH`): The central band should be red and the outer bands should be blue, not vice versa.
* Comoros (`KM`): As a symbol of Islam, the crescent (and stars) should probably not be distorted as they are.
* Sri Lanka (`LK`): The golden lion on the left side of the flag is completely missing.
* Mauritania (`MR`): The red stripes on the top and bottom are completely missing.
* Maldives (`MV`): The center is completely incorrect. It should not be blue, it should be green.

### PR DESCRIPTION
**Pull request by nanaya**
Should resolve #3760 once and for all (and any further complaints shall go to twemoji project instead :eyes: )

### CODE REVIEW

**Comment by peppy** [comment]
In brief experimentation, if we're looking to bring the colours back in line with how they used to be (because the new ones, while correct, look completely out of place IMO) applying `filter:saturate(90%) hue-rotate(-25deg)` or so feels *slightly* better?

Before:
20210720 183337 (Safari)

20210720 183323 (Safari)

After:

20210720 183823 (Safari)

20210720 183832 (Safari)

Probably need more opinions.

**Comment by notbakaneko** [comment]
While I agree the new ones have a bit too much contrast against the rest of the design, I don't think the hues should be colour shifted.

**Comment by peppy** [comment]
Any other suggestions? As it stands, I'm pretty against this change as a whole. We use these in so many places that this becomes an eyesore.

**Comment by nanaya** [comment]
Maybe a combination of white overlay and saturation adjustment? This is with 20% white overlay and 110% saturation

**Comment by peppy** [comment]
That seems closer to expectations. Potentially taking the whiteness a touch further even?

**Comment by nanaya** [comment]
@arflyte can you adjust the flag colour... thing (see comments above)? Live demo at https://osunext.dev.myconan.net/rankings/osu/performance

**Comment by peppy** [comment]
Looks pretty good at that URL (25% white overlay). I can live with that.

**Review by peppy — APPROVED** [review]

**Comment by peppy** [comment]
Dropping an approval on this one, but let's wait for a response from @arflyte before merging.

**Comment by arflyte** [comment]
Oh, I like ones with white overlay. Hopefully, no one complains that their flag colour is slightly inaccurate >_<

**Pull request merged**
