### PR TITLE
Locally cache groups data

### PR DESCRIPTION
**Pull request by nanaya**
File cache because apc is a pecl extension. Usual redis for versioning mechanism.

Initial cache may generate a few duplicates depending on the timing but hopefully it doesn't generate too many cache files. Especially tests (hence array driver).

### CODE REVIEW

**Review by notbakaneko — CHANGES_REQUESTED** [review]
- How does the cache get invalidated?
- How do previously cached entries expire/get removed?
- Should have note on why contents are stored locally since it's still hitting redis every time to get the version.

**Comment by peppy** [comment]
Not sure why it needs a version at redis in the first place? The only time this needs to be invalidated is when a new group is added right? I can just run artisan `cache:clear` or something (or just have it update on redeploy only).

**Comment by notbakaneko** [comment]
`cache:clear` deletes everything in the default cache and only that one; if it's redis, it flushes everything in the selected db.

**Comment by peppy** [comment]
yeah, i know i shouldn't run that command, but potentially another one that doesn't.

**Comment by nanaya** [comment]
It'll need to be run on all servers. And that may get more annoying when using docker or just when having more servers.

This way resetting the cache can be done from any one instance and can even be added to web/admin interface.

**Comment by peppy** [comment]
I guess, but also adding one RTT that we're trying to get rid of.

**Comment by nanaya** [comment]
might as well move the whole table to env file?

**Comment by peppy** [comment]
i think we should just go with this for now.

**Review by notbakaneko — APPROVED** [review]

**Pull request merged**
