### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by nanaya**
- missing experience bar fill
- less crappy move dialog

### CODE REVIEW

**Comment by nanaya** [comment]
after hours of debugging I managed to not figure out what's happening here :dancers:

**Comment by nanaya** [comment]
Still no idea what the problem is but at least splitting the test works ¯\\\_(ツ)_/¯

**Comment by peppy** [comment]
so is this ready to merge?

**Comment by nanaya** [comment]
yeah

**Pull request merged**
