### PR TITLE
Add all available locales field in wiki page API

### PR DESCRIPTION
**Pull request by gagahpangeran**
This changes is add other available locales of the wiki article for the API.

Also add the documentation.

### CODE REVIEW

**Review by cl8n — CHANGES_REQUESTED** [review]
style nitpick, the fields should be listed in alphabetical order, since they were before your change

**Review by notbakaneko — CHANGES_REQUESTED** [review]
for API usage, it should really list all `available_locales` instead

**Comment by gagahpangeran** [comment]
> for API usage, it should really list all `available_locales` instead

I just need to change the field name `other_locales` to `available_locales` but still using the function `otherLocales()` for it, am I right?

**Comment by notbakaneko** [comment]
`otherLocales()` doesn't include the current locale

**Comment by gagahpangeran** [comment]
Ah, I see. I just have to merge it with current locale.

**Review by notbakaneko — APPROVED** [review]
Would be nice if the locales were returned in order but that can be a separate issue.

**Pull request merged**
