### PR TITLE
Record new score id when pinning

### PR DESCRIPTION
**Pull request by nanaya**
First part of moving pinned score to new table. The column name is a bit unfortunate 🫥

Index to be added later as it should be unique but the current system allows pinning both legacy and imported score.

- [x] legacy score re-import or whatever solution for the incorrect import order ppy/osu-web#10725
- [x] ~~depends on #10922 as the score id should not change after this is merged and the linked issue may end with changing score id~~

~~Draft while looking into doing the whole thing in one go instead.~~ Nope

### CODE REVIEW

**Review by notbakaneko — APPROVED** [review]

**Comment by notbakaneko** [comment]
is this still waiting to the reimport task above? @peppy @nanaya

**Comment by peppy** [comment]
Yeah sorry, I'm making slow progress (see https://github.com/ppy/osu-web/issues/10725 for the latest).

**Comment by nanaya** [comment]
Oh yeah, the score id reordering thing apparently will be handled separately by @peppy so this can just go ahead.

**Comment by notbakaneko** [comment]
Would help if I pressed the update button too 👀

**Pull request merged**
