### PR TITLE
Don't increment replay counts if replay download is coming from an API request

### LINKED ISSUE #11019: Only increment "Replays watched" when downloading through lazer
I'm running a discord bot that downloads replays through the API to show stats like the UR and also render parts of the replay for analyzing and I've been getting a few reports of people being confused about their "Replays watched by Others" stat being increased by using the bot and thinking it might be a bug.

I'm thinking it might be better to only increment it when someone downloads the replay from lazer (e.g. actually watching it in-game). This would also help with potential abuse, as I've already seen people talking about "farming" this stat now.

### PR DESCRIPTION
**Pull request by tsunyoku**
Resolves #11019.

Took the direction peppy suggested as it makes sense to me, but I can change direction if something else is wanted.

### CODE REVIEW

**Comment by nanaya** [comment]
that function also returns true from lazer (also this won't help with abuse)

**Comment by tsunyoku** [comment]
> also returns true from lazer
right.. i forgot about that. do we have a pattern for detecting lazer request so we can allow it, or is this direction simply not going to work?

**Comment by nanaya** [comment]
I think the only way at the moment is checking the token client's `password_client` attribute

**Comment by respektive** [comment]
Correct me if I'm wrong, but wouldn't explicitly checking for the lazer oauth client_id work? Also I think it would still make sense to additionally only count the first download per user as nanaya suggested, to also avoid any abuse using the lazer api client.

**Comment by cl8n** [comment]
I don't agree with counting only one download per user; that seems like it would create an issue similar to #10961 but with a much more important metric. I think these counts should increment whenever web10 would do the same... so just a download counter, unless I'm missing something

**Comment by nanaya** [comment]
While not as strict as I'm proposing, web10 is actually doing something pretty close to it.

**Comment by cl8n** [comment]
superseded by #11126

**Pull request closed without merging**
