### PR TITLE
Featured stream shows as an embedded player on the livestreams page

### LINKED ISSUE #549: Highlighted stream on livestream page should be an embedded player
Right now it's a huge ugly thumbnail.

**[Bounty](https://goo.gl/nFdoyI) offered**: 20-50 depending on implementation quality.

Feel free to reply in this thread should you have any questions.

### PR DESCRIPTION
**Pull request by normundy**
Fixes #549

### CODE REVIEW

**Comment by LiquidPL** [comment]
Might be worth it to add 'Fixes #549' to the description to the issue gets closed automagically when the PR is merged.

**Comment by normundy** [comment]
Ok thanks LiquidPL

**Comment by nanaya** [comment]
quite sure this isn't how it's supposed to look like

**Comment by nekodex** [comment]
Also might want to avoid using inline CSS :wink:

**Comment by normundy** [comment]
TODO:
- Player adjusts accordingly to window size - will look at how the previous image for the featured stream was handled
- Separate out the inline CSS

**Comment by normundy** [comment]
Updated the pull request. Live stream info such as the view count and status are shown on top of the player now, and I took out the inline CSS. Will need the adjustments for @560 still but hopefully this will help.

osuweb_featuredstream2

osuweb_featuredstream2

**Pull request closed without merging**
