### PR TITLE
Remove country flags drop shadow

### PR DESCRIPTION
**Pull request by nanaya**
Apparently the shadow causes lag for some people. It was done that way because some flags are shaped differently.

People affected should check if this test page is actually smoother: https://osunext.dev.myconan.net/rankings/osu/performance

### CODE REVIEW

**Comment by peppy** [comment]
Still a bit weird when scrolling (I don't see this kind of behaviour on any other page) but by far a lot better:

https://user-images.githubusercontent.com/191335/127856054-7067a971-8f10-4f64-9ec1-b34067faecbd.MP4

**Comment by nanaya** [comment]
uh that was a wrong url :eyes:

**Comment by peppy** [comment]
Oops, iOS is weird with opening background tabs:

https://user-images.githubusercontent.com/191335/127856844-257dc703-5148-474d-a751-8d677a00714b.MP4

**Comment by notbakaneko** [comment]
With latest update:
https://user-images.githubusercontent.com/1694544/127861300-1fb557bc-48ba-47af-8e0e-fbf53c290197.mp4

**Review by notbakaneko — APPROVED** [review]

**Review by peppy — APPROVED** [review]

**Pull request merged**
