### PR TITLE
Ability to change store orders from admin page

### PR DESCRIPTION
**Pull request by echojc**
This is a work in progress for ppy/osu-web#109

- [x] Ability to edit address.
  - [x] Changes should be saved instantly.
- [ ] Ability to change product to another product of same value (different size/design) using a dropdown.
  - [ ] Changes should be saved instantly.
- [ ] Should only be allowed for orders in a "paid" state. Shipped or Delivered orders should not be changeable.
- [ ] Remaining stock should be checked (products without stock shouldn't be shown in the dropdown)
  - [ ] and updated on change.

### CODE REVIEW

**Comment by nanaya** [comment]
This controller is awesome™.

/s

Anyway, I believe it should at least look like this, route-wise

```
GET /store/admin/orders/{orderId}
PUT /store/admin/orders/{orderId}
PUT /store/admin/orders/{orderId}/items/{orderItemId}
```

And uses separate, namespaced controller

(now I look again, the work to change just this section probably isn't too bad)

**Comment by echojc** [comment]
With the PUT on order item, does it matter that `orderItemId` can already be used to directly reference the right row without needing the `orderId`? Would you check that they match (e.g., `where order_id = $a and id = $b`) before updating?

When you say use a separate namespaced controller, do you mean a new controller class with new routes in routes.php?

**Comment by nanaya** [comment]
> With the PUT on order item, does it matter that orderItemId can already be used to directly reference the right row without needing the orderId? Would you check that they match (e.g., where order_id = $a and id = $b) before updating?

Good point. I'm not sure if it's better to have the check one from OrderItem instead of done through Order, like, adding a method to update OrderItem from Order model - together the order state check etc.

> When you say use a separate namespaced controller, do you mean a new controller class with new routes in routes.php?

Yeah. Current `StoreController` scope is getting a bit too... big (it's currently doing p.much everything related to store).

**Comment by nanaya** [comment]
I just noticed there's already such method in Order model (`updateItem`). Comes with product stock updating logic as well.

**Comment by echojc** [comment]
Thanks, I'll take a look.

**Comment by nanaya** [comment]
Though looking what it does, it's probably not usable for this problem :confused:

**Comment by echojc** [comment]
@nanaya can you take a look at my store controller split before I carry on and add more stuff to it?

**Comment by nanaya** [comment]
I'm thinking something along this line http://laravel.com/docs/5.1/controllers#restful-resource-controllers with the controllers namespaced in `App\Http\Controllers\Store\Admin`

**Comment by echojc** [comment]
Third time lucky?

**Comment by nanaya** [comment]
looks about right (controller part).

**Comment by peppy** [comment]
I'm continuing work on this for what it's worth (can't wait any longer sorry!).

**Comment by peppy** [comment]
Closing this in favour of https://github.com/ppy/osu-web/pull/264. More to come.

**Pull request closed without merging**
