### PR TITLE
Uncap pp precision

### PR DESCRIPTION
**Pull request by pavlukivan**
I made this PR because of [this post](https://www.reddit.com/r/osugame/comments/e0xoel/mangomizer_sets_a_4994998_pp_score_but_it_says/)

SR is uncapped in API responses, so I think pp shouldn't be capped either

### CODE REVIEW

**Comment by mangomizer** [comment]
Actually, wasn't SR capped recently as well? Like I remember a time when we could get SR to 12 decimal places, now it's capped to 6 s.f.

**Comment by peppy** [comment]
4 decimal places is already more than enough. Strongly against this as being a step backwards.

**Comment by cl8n** [comment]
not sure if you meant to "fix" the thing in the reddit post, but this doesn't do it. 500pp is just 499.5 rounded up and that's not a truncated value
https://github.com/ppy/osu-web/blob/61ae2ce5670b203cad287755d3a776f74df16cbd/app/Transformers/ScoreTransformer.php#L57

**Comment by notbakaneko** [comment]
These aren't even used, it won't do anything

**Pull request closed without merging**
