### PR TITLE
Adjust recommended difficulty for taiko

### LINKED ISSUE #9626: Scaling did not change for Recommended Diffiuclty in osu!taiko
With the recent changes in osu!taiko resulting in a roughly 30-40% increase in pp for all users, the Recommended Difficulty did not change to reflect this and now I am being recommended 9* maps which is probably a little beyond my skill level.
image

### PR DESCRIPTION
**Pull request by nanaya**
Resolves #9626 except I don't see any agreement on it yet apart of one suggestion with one thumbs up and one other suggestion.

Feel free to discuss it further here.

For reference, current suggestions are:
1. [pp<sup>0.4</sup>&times;0.15](https://www.wolframalpha.com/input?i=x%5E0.4+*+0.15+with+0+%3C%3D+x+%3C+20000)
2. [pp<sup>0.35</sup>&times;0.27](https://www.wolframalpha.com/input?i=x%5E0.35+*+0.27+with+0+%3C%3D+x+%3C+20000)

Base chart if anyone wants to play around with the formula https://www.desmos.com/calculator/cgufjjnq1h

### CODE REVIEW

**Comment by Ratchet0203** [comment]
I'm not a dev so idk if I should say anything, but vunyunt's proposal is best imo. With mangomizer's 0.75 multiplier, I'd get recommended 5.78* maps, which at my level is far too easy. vunyunt's proposal, however, would recommend me 6.59* maps, which is much better. The current formula recommends me 7.51* maps, which I still struggle at. I have 9198pp.

**Comment by Alchyr** [comment]
I also agree with vunyunt's proposal, mango's is definitely a bit too low

**Comment by nanaya** [comment]
Also remember current recommended search has 0.5 range both ways...

**Comment by nanaya** [comment]
I guess we'll just go with this for now 🤨

**Review by notbakaneko — APPROVED** [review]

**Pull request merged**
