### PR TITLE
switch to proper many to many relationship

### PR DESCRIPTION
**Pull request by kschamplin19**
Should™ work.

### CODE REVIEW

**Comment by nanaya** [comment]
doesn't seem to bring much benefit (or at all at the moment) and even adds burden of manually casting date?

**Comment by kschamplin19** [comment]
its proper form. no need for a model for the pivot tables, plus you can just call $user->achievements() or $achievement->users().
of course if you don't like it that's fine, i think it's more clear this way.
also attaching an achievement is really simple, just $user->achievements()->attach($achievement_id)

**Comment by nanaya** [comment]
I don't seem to be able to find out how to set the bridge's date...

**Comment by kschamplin19** [comment]
pass an array as the second param when attaching.
$user->achievements()->attach($achievement_id, ["date" => "valid date"]);
updating is also possible
$user->achievements()->updateExistingPivot($achievement_id, $attributes);
[this is helpful](http://laraveldaily.com/pivot-tables-and-many-to-many-relationships/)
[official documentation](https://laravel.com/docs/5.1/eloquent-relationships#many-to-many)

**Comment by nanaya** [comment]
Looks not necessary for now. And adding support for casting the pivot attribute seems even worse (if work at all) ( https://laracasts.com/discuss/channels/general-discussion/cast-pivot-table-value-to-date )

**Comment by nanaya** [comment]
And the documentation for newPivot seems removed in 5.1...

**Comment by kschamplin19** [comment]
oh god ._.

yeah this is a pretty situational tool

closing.

**Pull request closed without merging**
