### PR TITLE
Add datadog increment wrapper

### PR DESCRIPTION
**Pull request by notbakaneko**
Not sure if useful but needing to prefix most of the time `$GLOBALS['cfg']['datadog-helper']['prefix_web']` seems repetitive 🤔  (and samplerate always being 1)

Renamed the `thumbdonger.*`counters to match the class name and removed the `processed` counter since its just the sum of the other 2.

### CODE REVIEW

**Comment by nanaya** [comment]
I wonder if we should just move everything (thumbs and chats) to `osu.web.` prefix

**Comment by nanaya** [comment]
it looks like osu-web is the only source now

**Comment by notbakaneko** [comment]
I propose renaming the `thumbdonger.*` stats to something else since the thumbnailer itself already sends its own stats...

**Comment by nanaya** [comment]
I guess we can look into renaming the metrics later and get this in first. Also maybe use named parameter and pass everything as is to the actual function?

**Review by nanaya — APPROVED** [review]

**Pull request merged**
