### PR TITLE
osu!wiki - add text-indent

### PR DESCRIPTION
**Pull request by MegaApplePi**
Indent the text by 2em, requested by @kj415j45 for Chinese

- add text-indent
- fix spacings for headings, lists, and images

### CODE REVIEW

**Comment by kj415j45** [comment]
maybe not only for Chinese :stuck_out_tongue:

**Comment by nanaya** [comment]
I don't understand what is this for.

**Comment by huoyaoyuan** [comment]
@nanaya It's wiki's stuff, we've discussed in the `osu-wiki` channel, and found that this should be the best way to adjust paragraph displaying, without adding many spaces in wiki source.

**Comment by nanaya** [comment]
Pretty sure if there is space between paragraphs, first line indent is not needed.

**Comment by MegaApplePi** [comment]
This was originally intended for Chinese*. @kj415j45 had mentioned in one of the osu-wiki prs that it was a custom/standard to indent the paragraphs for Chinese using 2 ideographic spaces/full width spaces.
It would have been either ~8 `&nbsp;` (nonbreaking spaces), 2 ideographic spaces/full-width spaces, or `text-indent: 2em;`.

I don't know if this is pointful but <http://gniw.ca/cjk-standard-paragraph-indent.php> and <https://medium.com/@bobtung/best-practice-in-chinese-layout-f933aff1728f> (see number 6) seems to in agreement that Chinese typically uses 2 ideographic spaces/full width spaces (or `text-indent: 2em;`) to separate their paragraphs, otherwise the layout will look weird.

\*_This was originally intended for Chinese_; however, @kj415j45 and I just thought it looked a bit more appealing for most pages anyways.

**Comment by nanaya** [comment]
Second link, "WEBish" style says use extra space between paragraphs.

**Comment by kj415j45** [comment]
Well, if it is not suitable to English(or other language), I may add it to `.wiki-content_zh` or mention it in Chinese Article Style Guide

**Comment by nanaya** [comment]
The reference linked mentions either use "first line indentation without spacing between paragraphs" or "no indentation with spacing between paragraphs". And we're already using the latter one.

Also from some random Chinese websites I checked (baidu, chinatimes), none of them use indented style either.

**Comment by kj415j45** [comment]
image

current spacing between paragraphs is enough?

**Comment by nanaya** [comment]
The paragraphs' `margin-bottom` can indeed use `1em` (or a bit more) instead of current `10px`.

**Comment by nanaya** [comment]
`1em` at `font-size` `14px` is `14px`...

**Comment by kj415j45** [comment]
......my fault, well, depends on you, since is not very neccessary to add text-indent

**Comment by MegaApplePi** [comment]
Alrighty then, should I close this pr and change the bottom margin to `margin-bottom: 1em;` in another or or should I just change it in this pr?

**Comment by nanaya** [comment]
make a new branch is probably easier.

**Comment by MegaApplePi** [comment]
alrighty

**Pull request closed without merging**
