### PR TITLE
Increase Beatmap Discussion auto refresh interval to 30 seconds

### PR DESCRIPTION
**Pull request by notbakaneko**
Maybe 10 seconds is too frequent if changes keep happening 🤔

### CODE REVIEW

**Review by nanaya — APPROVED** [review]
sure 🤷

**Comment by peppy** [comment]
I do wonder if at the point it's 30 seconds, people are just going to be refreshing the page anyway. Like unless there's something visually showing the user that there's polling / auto-refreshing going on, a lot of users aren't going to realise and just reload the page out of habit.

**Comment by peppy** [comment]
Maybe just remove it altogether >_>

**Comment by notbakaneko** [comment]
We decided to try a different thing for this instead

**Pull request closed without merging**
