### PR TITLE
Docker update

### PR DESCRIPTION
**Pull request by nanaya**
- add deployment container
  - [x] currently missing documentation
- update development env
  - now with working phpunit and dusk and karma
  - also job queue
  - one image for all the php/dependencies stuff
- removed bootstrap from docker-compose
- removed migration from docker-compose

### CODE REVIEW

**Comment by Pennek** [comment]
hey, reporting in with my experiences with the new setup procedure.

I encountered [this](https://i.imgur.com/A8W0iB3.png) error while generating assets for a new Docker environment. No idea how or why it happens. If you need any additional info I'll be happy to provide it

**Comment by nanaya** [comment]
@Pennek can you share the full output of `docker-compose logs assets`? And `docker-compose ps`.

**Comment by notbakaneko** [comment]
@Pennek does it happen consistently?

**Comment by Pennek** [comment]
Yes, this happens consistently. Here are the requested files: [asset logs](https://pastebin.com/zCieuxY8), [ps](https://pastebin.com/2jGf26eK)

**Comment by nanaya** [comment]
Update and try again.

**Comment by Pennek** [comment]
Updated and tried again. I got another error. Logs: [assets](https://pastebin.com/q0GYWDvz) [ps](https://pastebin.com/SpKQW8JH)

**Comment by nanaya** [comment]
@Pennek as it turned out there are some problems running docker commands under Windows. Please check the updated setup guide and try again.

**Pull request merged**
