### PR TITLE
Expose playlist item's playlist_order in JSON responses

### PR DESCRIPTION
**Pull request by smoogipoo**
I think we probably want to upgrade this column to a mediumint / int, but that can be done in the future.

### CODE REVIEW

**Comment by peppy** [comment]
missed the comma again

**Comment by peppy** [comment]
> I think we probably want to upgrade this column to a mediumint / int, but that can be done in the future.

`smallint` will allow some 32768 items, is there something i'm missing with how this is going to be used? if we get that high in a room, there are going to be other issues that arise first.

**Comment by smoogipoo** [comment]
The case I foresee is a large round robin room which lasts for a very long time, with many people joining. If I'm storing the gameplay order of all items _historically_, then I'm worried that we can overflow this value.

So one of two things has to happen: either the limit should be increased, or we cannot rely on this for historical ordering and need to use the `updated_at` column as I initially proposed.

**Comment by peppy** [comment]
I don't think that's important to think about right now. Like, before that, the room is going to get so large in request size that things will fall over. Far before we get anywhere near the 30k limit.

**Review by peppy — APPROVED** [review]

**Pull request merged**
