### PR TITLE
Beatmap updates

### PR DESCRIPTION
**Pull request by nanaya**
Namespaced react files, variable-width beatmapset panel, 10 difficulties icon before the +.

### CODE REVIEW

**Comment by nekodex** [comment]
Probably worthwhile doing a git mv on beatmaps.coffee -> main.coffee so we don't lose file history

**Comment by nekodex** [comment]
Also alignment broken (when not-logged in and elasticsearch isn't running)...

Maybe worthwhile showing a different error message (later)

**Comment by nanaya** [comment]
the old file still there confuses git(hub)

```
[detached HEAD 9eb555e] Namespace beatmaps react
 12 files changed, 49 insertions(+), 292 deletions(-)
 rename resources/assets/coffee/react/{beatmaps/difficulty-icon.coffee => _components/beatmap-difficulty-icon.coffee} (100%)
 rename resources/assets/coffee/react/{beatmaps/panel.coffee => _components/beatmapset-panel.coffee} (98%)
 rewrite resources/assets/coffee/react/beatmaps.coffee (89%)
 create mode 100644 resources/assets/coffee/react/beatmaps/_base.coffee
 rename resources/assets/coffee/react/{beatmaps.coffee => beatmaps/main.coffee} (94%)
 rename resources/assets/coffee/react/beatmaps/{pagination.coffee => paginator.coffee} (92%)
```

**Comment by nekodex** [comment]
@nanaya did you want to check my fixes before I merge this?

**Comment by nanaya** [comment]
seems fine apart of needing another update branch.

**Pull request merged**
