### PR TITLE
Adjust dashboard banner position

### PR DESCRIPTION
**Pull request by nanaya**
The glow is kinda intentional 👀

### CODE REVIEW

**Review by peppy — APPROVED** [review]
Went through design changes IRL 👍  Better than what we have live so let's get this out and then work forward from there.

**Comment by notbakaneko** [comment]
Is the glow supposed to bleed everywhere?

**Comment by nanaya** [comment]
yes

**Review by notbakaneko — CHANGES_REQUESTED** [review]
umm
image
image
image

(also it's kind of hard to tap anything other than the banner link on mobile)

**Comment by nanaya** [comment]
yeah I'm not sure why the indicator button isn't clickable on the content padding area ಠ_ಠ

**Review by notbakaneko — APPROVED** [review]

**Pull request merged**
