### PR TITLE
Mysql Sucks.

### PR DESCRIPTION
**Pull request by nanaya**
This is test part 2.

### CODE REVIEW

**Comment by nanaya** [comment]
so a pull request from local branch (same user) sets the addons (mariadb 10.0) correctly but not when from another user.

**Comment by kcaze** [comment]
Looks like it's still failing? I'm also not seeing the logs anymore, but I'm guessing that's a Travis issue: https://www.traviscistatus.com/

**Comment by peppy** [comment]
Closing for now :-1:

**Pull request closed without merging**
