### PR TITLE
Allow organising news posts by year

### LINKED ISSUE #9279: Support per-year news posts directory
Current `/news/` in osu-wiki repo is getting a bit too large and can't be browsed in full from the web anymore (truncated listing). Moving them to subdirectories by year should help but it needs to be supported here first.

### PR DESCRIPTION
**Pull request by nanaya**
Maybe? 🤷 

Resolves #9279

### CODE REVIEW

**Review by notbakaneko — APPROVED** [review]
Seems fine, need to arrange for the wiki to be updated for the existing articles to link to the correct entry.

**Comment by nanaya** [comment]
this should work with either directory structure so the actual structure can be updated whenever after this is deployed

**Comment by TicClick** [comment]
perhaps I am late to the party, but we also had an idea of grouping news by whatever project they belong to -- see https://github.com/ppy/osu-wiki/issues/2247. I don't have a strong opinion here (nor this should block the PR), but maybe @cl8n or @Joehuu do

**Comment by cl8n** [comment]
that issue seems like tangential idea that can still happen later if it's wanted
this pr looks good to me

**Comment by notbakaneko** [comment]
The link back to the github back is always `yyyy/slug-name` even if the page isn't actually in the directory

**Comment by nanaya** [comment]
the slug isn't available to anyone but admin and wiki people can't actually change the structure yet as it won't work without this...

**Pull request merged**
