### PR TITLE
Support displaying legacy total score

### PR DESCRIPTION
**Pull request by nanaya**
Prioritise displaying it if available. There's a different problem that there's no indication whether the score is legacy or lazer though 🤷

### CODE REVIEW

**Comment by smoogipoo** [comment]
Also, scores submitted from lazer must not have this set, if that isn't already checked (can't see such a check at a glance).

**Comment by nanaya** [comment]
Only fields specified in the [controller](https://github.com/ppy/osu-web/blob/0fc2b21cbaa3b7729c4013ade2ddfdc5584ad1c8/app/Http/Controllers/Solo/ScoresController.php#L32-L50) are stored.

**Comment by smoogipoo** [comment]
Oh, so that doesn't include `maximum_statistics`? That's an issue.

**Comment by nanaya** [comment]
That is indeed. And should be fixed by #9233.

**Review by notbakaneko — APPROVED** [review]

**Pull request merged**
