### PR TITLE
Convert [profile] bbcode to [url] at post time

### PR DESCRIPTION
**Pull request by cl8n**
backend part of #4050 . now on the forum they end up missing the bold and user card since they're plain urls, but that should be the behavior of any url with a user link

### CODE REVIEW

**Comment by nanaya** [comment]
Before you go on creating a url parser for that user card, maybe try extending the syntax to allow passing uid `[profile=uid]uname[/profile]` and automatically add it on store if missing.

**Comment by cl8n** [comment]
that'd work too, but I was thinking the user card would be wanted even if you wrote in a user [url]. if that's not the case I'll change

**Comment by nanaya** [comment]
I have a feeling adding support for user card on any (forum post?) links will be rather complex.

**Comment by nanaya** [comment]
Apparently I forgot to mention that I need to see how the front-end change look like first before continuing this.

**Pull request merged**
