### PR TITLE
Update email recovery process link in account verification dialog

### LINKED ISSUE #8969: 'email recovery process' link in account verification dialog is outdated
image

The current link redirects multiple times:

image

Should probably be changed to https://osu.ppy.sh/wiki/en/Help_centre/Account#sign-in

### PR DESCRIPTION
**Pull request by jhdcruz**
Fixes #8969

### CODE REVIEW

**Review by peppy — APPROVED** [review]

**Comment by The-Last-Cookie** [comment]
Will this also work for localised articles? German for example has [`#anmeldung`](https://osu.ppy.sh/wiki/de/Help_centre/Account#anmeldung) as the title for the `sign-in` section.

**Comment by peppy** [comment]
I'd hope so.

**Comment by nanaya** [comment]
The wiki page for other languages should be updated to have same id. The english one should probably also be hardcoded with the id so the link won't break if the title changes.

**Comment by TicClick** [comment]
> The wiki page for other languages should be updated to have same id

I have that on my radar

**Pull request merged**
