### PR TITLE
Adjust timeout to match proxy

### PR DESCRIPTION
**Pull request by nanaya**
- [ ] check if there's anything that's been running for over a minute without the return code being confirmed (mainly for interop endpoint?)

### CODE REVIEW

**Comment by notbakaneko** [comment]
I remember contest admin downloads taking too long or something 🤔

**Comment by nanaya** [comment]
I think I've fixed that one by streaming the response

**Comment by nanaya** [comment]
hmm, I wonder if it's still needed once the transfer is started

**Comment by nanaya** [comment]
need to fix this through a different method.

**Pull request closed without merging**
