### PR TITLE
Ignore kudosu on deleted beatmaps

### PR DESCRIPTION
**Pull request by nanaya**
...maybe?

### CODE REVIEW

**Comment by nekodex** [comment]
we probably need something to trigger recalculation of kudosu when beatmaps are deleted to make this useful?

**Comment by nanaya** [comment]
I'm thinking somewhere in legacy interop controller thingy as part of refresh beatmapset cache.

**Comment by Xinnoh** [comment]
Don't think this should be added, people can still make valid suggestions while a map is uploaded. Just because it's deleted doesn't mean they put in effort to mod it

**Comment by Mirruuu** [comment]
I agree with Sinnoh, even if the difficulty is deleted the input was still valuable. It shouldn't be rendered moot if the difference is deleted.

**Comment by nekodex** [comment]
After some discussion, we've decided this is probably not the best approach to take. Gonna close this in favour of #2308 to handle kudosu on deleted beatmaps for the time being.

**Pull request closed without merging**
