### PR TITLE
Update difficulty color bracket thresholds

### PR DESCRIPTION
**Pull request by Poyo-SSB**
It's been a long time since the color brackets for difficulties were touched. Lots has changed in the star-rating system and community since then. This PR updates the thresholds to reflect that.

To numerically justify this change, I've analyzed every ranked osu!standard beatmap containing one of a number of different difficulty keywords in its version name and plotted them by time vs. difficulty, showing clear striation:

plot

(Outliers include "[**Hard**est](https://osu.ppy.sh/beatmapsets/662526#osu/1402392)" and "[s**hard**ex's Extra](https://osu.ppy.sh/beatmapsets/819112#osu/1720423).") Note that the highest difficulty category is "Extra"—this is practically synonymous with "Expert" as the two terms occupy the same vertical space, but "Extra" is simply used more frequently than "Expert" (1863 maps vs. 576 maps). "Expert" has only begun to see common use in the last year and a half.

There are several other labels frequently used which are not shown on this chart, but for which statistics were collected, including:

* Beginner: 0.50★–2.00★ — Easy with a lower minimum
* Advanced: 2.30★–3.30★ — an intermediate between Normal and Hard
* Hyper: 3.30★–4.55★ — an intermediate between Hard and Insane
* Another: 4.25★–5.70★ — an intermediate between Insane and Expert
* Extreme: 5.50★–7.15★ — an additional category above Expert

**Note that this analysis was done on only osu!standard beatmaps—ideally, separate thresholds would be used for each other mode.**

Raw statistics ([excel file](https://github.com/ppy/osu-web/files/2864370/osu-difficulties.xlsx)):

```
╔═══════════╦══════╦══════╦══════╦══════╗
║           ║ X̄    ║ σ    ║ X̄−2σ ║ X̄+2σ ║
╠═══════════╬══════╬══════╬══════╬══════╣
║  Beginner ║ 1.57 ║ 0.31 ║ 0.95 ║ 2.19 ║
║ >Easy     ║ 1.64 ║ 0.23 ║ 1.18 ║ 2.11 ║
║ >Normal   ║ 2.11 ║ 0.28 ║ 1.55 ║ 2.67 ║
║  Advanced ║ 2.80 ║ 0.46 ║ 1.87 ║ 3.73 ║
║ >Hard     ║ 3.25 ║ 0.44 ║ 2.37 ║ 4.13 ║
║  Hyper    ║ 3.79 ║ 0.52 ║ 2.74 ║ 4.83 ║
║ >Insane   ║ 4.36 ║ 0.55 ║ 3.27 ║ 5.45 ║
║  Another  ║ 4.88 ║ 0.55 ║ 3.78 ║ 5.98 ║
║  Expert   ║ 5.31 ║ 0.69 ║ 3.93 ║ 6.68 ║
║ >Extra    ║ 5.64 ║ 0.46 ║ 4.72 ║ 6.56 ║
║  Extreme  ║ 5.64 ║ 0.86 ║ 3.91 ║ 7.37 ║
╚═══════════╩══════╩══════╩══════╩══════╝
```

---

Updates the star ratings each difficulty colour is associated with.

### CODE REVIEW

**Comment by peppy** [comment]
That chart is amazing

**Comment by Poyo-SSB** [comment]
I applied the same process to osu!taiko.

plot

Results are, er, inconclusive.

Labels not included:

* Ura Oni: 5.00★–7.00★ — Synonymous with Inner Oni
* Hell Oni: 6.00★–8.00★ — Harder than Inner Oni

Raw statistics ([excel file](https://github.com/ppy/osu-web/files/2867469/taiko-difficulties.xlsx)):

```
╔═════════════╦══════╦══════╦══════╦══════╗
║             ║ X̄    ║ σ    ║ X̄−2σ ║ X̄+2σ ║
╠═════════════╬══════╬══════╬══════╬══════╣
║ >Kantan     ║ 1.47 ║ 0.29 ║ 0.88 ║ 2.06 ║
║ >Futsuu     ║ 2.15 ║ 0.32 ║ 1.51 ║ 2.80 ║
║ >Muzukashii ║ 2.86 ║ 0.41 ║ 2.04 ║ 3.67 ║
║ >Oni        ║ 3.94 ║ 0.76 ║ 2.43 ║ 5.45 ║
║ >Inner Oni  ║ 5.01 ║ 0.85 ║ 3.31 ║ 6.70 ║
║  Ura Oni    ║ 5.08 ║ 1.02 ║ 3.03 ║ 7.13 ║
║  Hell Oni   ║ 6.29 ║ 0.87 ║ 4.55 ║ 8.02 ║
╚═════════════╩══════╩══════╩══════╩══════╝
```

**Comment by Poyo-SSB** [comment]
osu!catch:

plot

I couldn't find any additional labels which represent similar difficulty ranges. Deluge, a fairly well-accepted term, per se has only seven samples.

Raw statistics ([excel file](https://github.com/ppy/osu-web/files/2867696/catch-difficulties.xlsx)):

```
╔═══════════╦══════╦══════╦══════╦══════╗
║           ║ X̄    ║ σ    ║ X̄−2σ ║ X̄+2σ ║
╠═══════════╬══════╬══════╬══════╬══════╣
║ >Rain     ║ 3.95 ║ 0.45 ║ 3.05 ║ 4.85 ║
║ >Platter  ║ 2.88 ║ 0.33 ║ 2.22 ║ 3.53 ║
║ >Salad    ║ 1.95 ║ 0.23 ║ 1.49 ║ 2.41 ║
║ >Cup      ║ 1.35 ║ 0.19 ║ 0.97 ║ 1.73 ║
║ >Overdose ║ 5.17 ║ 0.62 ║ 3.93 ║ 6.42 ║
║ >Deluge   ║ 5.91 ║ 0.86 ║ 4.19 ║ 7.63 ║
╚═══════════╩══════╩══════╩══════╩══════╝
```

**Comment by Poyo-SSB** [comment]
osu!mania:

plot

osu!mania maps, drawing inspiration from a wide variety of sources, have far more alternate labels than any other mode (easy/ez/basic, normal/nm/novice, etc.). These have been merged into the more standard labels.

Not included in the plot:

* Beginner: 0.70★–1.50★ — Easy with a lower minimum
* Hyper: 2.45★–3.55★ — an intermediate between Hard and Insane

Raw statistics ([excel file](https://github.com/ppy/osu-web/files/2868062/mania-difficulties.xlsx)):

```
╔═══════════╦══════╦══════╦══════╦══════╗
║           ║ X̄    ║ σ    ║ X̄−2σ ║ X̄+2σ ║
╠═══════════╬══════╬══════╬══════╬══════╣
║  Beginner ║ 1.28 ║ 0.26 ║ 0.75 ║ 1.80 ║
║ >Easy     ║ 1.31 ║ 0.20 ║ 0.92 ║ 1.70 ║
║ >Normal   ║ 1.89 ║ 0.23 ║ 1.43 ║ 2.35 ║
║ >Hard     ║ 2.88 ║ 0.42 ║ 2.04 ║ 3.73 ║
║  Hyper    ║ 3.06 ║ 0.49 ║ 2.08 ║ 4.05 ║
║ >Insane   ║ 3.91 ║ 0.55 ║ 2.81 ║ 5.00 ║
║ >Another  ║ 4.27 ║ 0.64 ║ 3.00 ║ 5.55 ║
║ >Extra    ║ 4.94 ║ 0.83 ║ 3.27 ║ 6.61 ║
╚═══════════╩══════╩══════╩══════╩══════╝
```

**Comment by Krystool** [comment]
@Poyo-SSB Update your branch.

**Comment by Poyo-SSB** [comment]
Little has changed in the past two weeks, but here's a chart which combines "Expert" and "Extra" for better visualization.

plot

Raw statistics ([excel file](https://github.com/ppy/osu-web/files/2899152/osu-difficulties.xlsx)):

```
╔═══════════════╦══════╦══════╦══════╦══════╗
║               ║ X̄    ║ σ    ║ X̄−2σ ║ X̄+2σ ║
╠═══════════════╬══════╬══════╬══════╬══════╣
║  Beginner     ║ 1.57 ║ 0.31 ║ 0.96 ║ 2.19 ║
║ >Easy         ║ 1.64 ║ 0.23 ║ 1.18 ║ 2.11 ║
║ >Normal       ║ 2.11 ║ 0.28 ║ 1.55 ║ 2.67 ║
║  Advanced     ║ 2.80 ║ 0.46 ║ 1.88 ║ 3.73 ║
║ >Hard         ║ 3.25 ║ 0.44 ║ 2.37 ║ 4.13 ║
║  Hyper        ║ 3.78 ║ 0.53 ║ 2.72 ║ 4.84 ║
║ >Insane       ║ 4.36 ║ 0.55 ║ 3.27 ║ 5.45 ║
║  Another      ║ 4.89 ║ 0.55 ║ 3.78 ║ 5.99 ║
║ >Extra/Expert ║ 5.56 ║ 0.54 ║ 4.48 ║ 6.64 ║
║  Extreme      ║ 5.65 ║ 0.87 ║ 3.92 ║ 7.38 ║
╚═══════════════╩══════╩══════╩══════╩══════╝
```

**Comment by abraker95** [comment]
There are also some sets that use "Ultra" as a diff name

**Comment by Poyo-SSB** [comment]
I found 52 difficulties with "Ultra" in their name, which is by far the fewest difficulties of any collected label. The next smallest, "Extreme," has four times that (257). Compare that to the label with the most difficulties, "Normal," with 12162 difficulties.

**Comment by peppy** [comment]
I think we can go ahead with this as there has been little contention against it. If possible, could you please make (or find a good) wiki page to list these under?

**Comment by sharudesu** [comment]
"shardex's Extra" that's me

**Pull request merged**
