### PR TITLE
Surround query with quotes when clicking on title, artist or source on beatmapset page

### LINKED ISSUE #8841: Increase the search accuracy when clicking source's super link on map's description
In my recent practice on deciding whether i should put the full event name"THE BMS OF FIGHTERS XVI -NEO DYSTOPIA-" or abbreviation"BOFXVI" on my map's source 
Turns out i just discovered how misleading putting full BOFXVI event name into source:
https://media.discordapp.net/attachments/951524313763287071/967182643651297300/unknown.png?width=474&height=671
when i click the source on my map's desc and it lead you to map searching page and none of them are legit from the event:<
but with Abbreviation"BOFXVI" it's a lot relevant:
https://cdn.discordapp.com/attachments/849692819799277578/967192792910659614/unknown.png

As a very clueless mapper myself i asked other experienced mappers how can i solve this and they said you can customize in beatmap searching:
Mapper: The reason why you see so many bad result is cuz of THE
which is very common word
only search keyword with fuzzy search (without quotes)
if u know exactly what u want, always use ""

that did answered my problem but another question came to my mind
why they don't put the "" automatically? when leading to beatmap searching from map's description?
Cause what you put in source should be seen as a whole instead of separated letters.
Manually adding that like the current one is fine but seems like a easier way tis to fix it for everyone that not knowing this searching tech beforehand!

An alternative:
Having a button as default 
Like with " or not
Search by a whole phrase
Search by each in search engine is also a solution

Hoping this issue will be reviewed so i can put my epic event name on my map before qualified(X
I mean,increase the total search accuracy on the website:>

### PR DESCRIPTION
**Pull request by Swekka**
- [x] Depends on #10718

Closes #8841

### CODE REVIEW

**Review by nanaya — CHANGES_REQUESTED** [review]
It's not quite working yet (to be improved by #10716) but it should be double (double) quoted (`title=""the title""`).

**Comment by Swekka** [comment]
Isn't it planned to use `title="the title"!` for full matching? (#10377)

**Comment by nanaya** [comment]
I don't know when that will happen. Adding support for that is a bit more involved. The double double quoting is for searching the words in specified order.

**Comment by Swekka** [comment]
Oh, I see, I thought single quotes already did that.

**Review by nanaya — APPROVED** [review]

**Pull request merged**
